name: Sentence
description: A Flutter app for managing documents and notes.
version: 1.0.1+1

environment:
  sdk: ">=3.2.0 <4.0.0"
dependencies:
  dynamic_color: ^1.7.0
  flutter_launcher_icons: ^0.14.3
  flutter_quill: ^5.4.0
  shared_preferences: ^2.5.3
  image_picker: ^1.1.2
  file_picker: ^10.1.9
  path_provider: ^2.1.5
  permission_handler: ^12.0.0
  flutter_speed_dial: ^6.2.0
  animations: ^2.0.11
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
flutter:
  uses-material-design: true
flutter_icons:
  android: true
  ios: false
  image_path: "android/app/src/main/res/mipmap-hdpi/ic_launcher.png"
